services:
  admin:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${org}/flowise.git#${FLOWISE_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      args:
        REACT_APP_UCI_API: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/uci-apis
        REACT_APP_SOCKET_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/transport-socket
        REACT_APP_REGISTRY_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/nodehub
        SERVE_PATH: "/flowise"
    restart: always
