services:  
  dataset_service:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/dataset-service:${DATASET_SERVICE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${DATASET_SERVICE_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${DATASET_SERVICE_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    environment: 
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/dataset_service"
      MINIO_ENDPOINT: "cdn-api.${DOMAIN_NAME}"
      MINIO_SECURE_CONN: "True"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: dataset-service
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 9
      AI_TOOLS_EMBEDDING_BASE_URL: ${AI_TOOLS_BASE_URL}
      AI_TOOLS_BATCH_SIZE: ${AI_TOOLS_EMBEDDING_BATCH_SIZE}