services:
  app:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${org}/kisai-bot.git#${APP_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      args:
        NEXT_PUBLIC_BOT_ID: ${NEXT_PUBLIC_BOT_ID}
        NEXT_PUBLIC_CONFIG_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/deployer/deployment/config/${NEXT_PUBLIC_BOT_ID}
        NEXT_PUBLIC_BOT_NAME: ${NEXT_PUBLIC_BOT_NAME}
        NEXT_PUBLIC_SOCKET_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}
        NEXT_PUBLIC_TELEMETRY_API: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/telemetry
        NEXT_PUBLIC_AI_TOOLS_API: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/ai-tools-proxy
        NEXT_PUBLIC_BFF_API_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/bff
        NEXT_PUBLIC_USER_SERVICE_APP_ID: ${NEXT_PUBLIC_USER_SERVICE_APP_ID}
        NEXT_PUBLIC_JWKS_URI: 'http://fusionauth:9011/.well-known/jwks.json'
        NEXT_PUBLIC_USER_SERVICE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/user
        NEXT_PUBLIC_ORG_ID: ${NEXT_PUBLIC_ORG_ID}
        NEXT_PUBLIC_DEBUG: ${NEXT_PUBLIC_DEBUG}
        NEXT_PUBLIC_SOCKET_PATH: '/transport-socket/socket.io'
        NEXT_PUBLIC_GOOGLE_KEY: ${NEXT_PUBLIC_GOOGLE_KEY}
        FUSIONAUTH_URL: http://fusionauth:9011/
        FUSIONAUTH_KEY: ${FUSIONAUTH_KEY}
        NEXT_PUBLIC_DATASET_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/dataset-service
        NEXT_PUBLIC_ENTITY_DATASET_ID: ${NEXT_PUBLIC_ENTITY_DATASET_ID}
        NEXT_PUBLIC_CLARITY_PROJECT_ID: ${NEXT_PUBLIC_CLARITY_PROJECT_ID} 
        NEXT_PUBLIC_SHOW_ONBOARDING: ${NEXT_PUBLIC_SHOW_ONBOARDING}
        NEXT_PUBLIC_WEATHER_API: ${NEXT_PUBLIC_WEATHER_API}
       